export const tshirts = [
  [
    {
      id: 1,
      name: "Classic Tee",
      oldPrice: 30,
      price: 25,
      quantity: 1,
      avlColors: ["black", "white", "grey"],
      src: "/data/classictee.jpeg",
      catigory: "tshirt",
      addedToCart: false,
      wished: false,
      discription: "Comfortable classic tee for everyday wear.",
    },
    {
      id: 2,
      name: "Vintage Tee",
      oldPrice: 35,
      price: 27,
      quantity: 1,
      avlColors: ["navy", "grey", "white"],
      src: "/data/vintagetee.jpeg",
      catigory: "tshirt",
      addedToCart: false,
      wished: false,
      discription: "A vintage-style tee for a unique look.",
    },
    {
      id: 3,
      name: "Graphic Tee",
      oldPrice: 32,
      price: 30,
      quantity: 1,
      avlColors: ["red", "white", "blue"],
      src: "/data/graphic tee.jpeg",
      catigory: "tshirt",
      addedToCart: false,
      wished: false,
      discription: "Stylish tee with a cool graphic print.",
    },
    {
      id: 5,
      name: "Logo Tee",
      oldPrice: 40,
      price: 35,
      quantity: 1,
      avlColors: ["green", "black", "white"],
      src: "/data/logotee.png",
      catigory: "tshirt",
      addedToCart: false,
      wished: false,
      discription: "Featuring our logo for a bold look.",
    },
    {
      id: 4,
      name: "Striped Tee",
      oldPrice: 28,
      price: 22,
      quantity: 1,
      avlColors: ["blue", "black", "white"],
      src: "/data/stripedtee.jpeg",
      catigory: "tshirt",
      addedToCart: false,
      wished: false,
      discription: "Striped tee, perfect for casual outings.",
    },
    {
      id: 6,
      name: "Plain White Tee",
      oldPrice: 32,
      price: 29,
      quantity: 1,
      avlColors: ["white"],
      src: "/data/PlainWhiteTee.jpeg",
      catigory: "tshirt",
      addedToCart: false,
      wished: false,
      discription: "Plain white tee, a wardrobe essential.",
    },
  ],
  [
    {
      id: 16,
      name: "Winter Hoodie",
      oldPrice: 60,
      price: 45,
      quantity: 1,
      avlColors: ["black", "white", "navy"],
      src: "/data/Cool Fluffy Snuddie Hoodies For Men, Men's Casual Polar Fleece Pullover Hooded Sweatshirt Streetwear For Winter Fall, As Gifts - Apricot _ S(36).jpeg",
      catigory: "hoodie",
      addedToCart: false,
      wished: false,
      discription: "Warm and comfortable hoodie for winter.",
    },
    {
      id: 17,
      name: "Fleece Hoodie",
      oldPrice: 55,
      price: 40,
      quantity: 1,
      avlColors: ["grey", "black", "blue"],
      src: "/data/Reiss Black Cotton Fleece-Back Hoodie, XS.jpeg",
      catigory: "hoodie",
      addedToCart: false,
      wished: false,
      discription: "Soft fleece hoodie for extra warmth.",
    },
    {
      id: 18,
      name: "Zip-Up Hoodie",
      oldPrice: 65,
      price: 50,
      quantity: 1,
      avlColors: ["black", "green"],
      src: "/data/Mens Next Black Zip Through Borg Fleece Lined Zip Through Hoodie -  black.jpeg",
      catigory: "hoodie",
      addedToCart: false,
      wished: false,
      discription: "Easy-to-wear zip-up hoodie.",
    },
    {
      id: 19,
      name: "Pullover Hoodie",
      oldPrice: 58,
      price: 44,
      quantity: 1,
      avlColors: ["white", "red", "black"],
      src: "/data/Men's Loose Fit Knit Hoodie With Pockets, Long Sleeve.jpeg",
      catigory: "hoodie",
      addedToCart: false,
      wished: false,
      discription: "Classic pullover hoodie for everyday use.",
    },
    {
      id: 20,
      name: "Sports Hoodie",
      oldPrice: 70,
      price: 55,
      quantity: 1,
      avlColors: ["navy", "grey"],
      src: "/data/Mens adidas Green House of Tiro Fleece Hoodie -  green.jpeg",
      catigory: "hoodie",
      addedToCart: false,
      wished: false,
      discription: "Ideal for workouts and sports activities.",
    },
    {
      id: 21,
      name: "Graphic Hoodie",
      oldPrice: 62,
      price: 48,
      quantity: 1,
      avlColors: ["black", "white", "purple"],
      src: "/data/Mens Oversized Love Is In The Air Puff Print Hoodie - Black - M.jpeg",
      catigory: "hoodie",
      addedToCart: false,
      wished: false,
      discription: "Hoodie with a cool graphic design.",
    },
  ],
  [
    {
      id: 31,
      name: "Casual Pants",
      oldPrice: 50,
      price: 40,
      quantity: 1,
      avlColors: ["black", "khaki", "grey"],
      src: "/data/Mens Next Light Stone Straight Fit Cotton Stretch Cargo Trousers -  light stone.jpeg",
      catigory: "pants",
      addedToCart: false,
      wished: false,
      discription: "Comfortable casual pants for daily wear.",
    },
    {
      id: 32,
      name: "Slim Fit Jeans",
      oldPrice: 65,
      price: 50,
      quantity: 1,
      avlColors: ["blue", "black"],
      src: "/data/Devil-Dog Dungarees Slim Straight Leg Jeans in Biscoe at Nordstrom, Size 32 X 34.jpeg",
      catigory: "pants",
      addedToCart: false,
      wished: false,
      discription: "Slim fit jeans with a modern style.",
    },
    {
      id: 33,
      name: "Chino Pants",
      oldPrice: 55,
      price: 45,
      quantity: 1,
      avlColors: ["khaki", "navy"],
      src: "/data/TAPERED FIT Traveler Chino Pants for Tall Men in Light Khaki - 34 _ 38 _ Light Khaki.jpeg",
      catigory: "pants",
      addedToCart: false,
      wished: false,
      discription: "Stylish chinos for a smart look.",
    },
    {
      id: 34,
      name: "Jogger Pants",
      oldPrice: 40,
      price: 35,
      quantity: 1,
      avlColors: ["black", "grey"],
      src: "/data/Rsq Twill Cargo Jogger Pants.jpeg",
      catigory: "pants",
      addedToCart: false,
      wished: false,
      discription: "Comfortable joggers for a relaxed fit.",
    },
    {
      id: 35,
      name: "Cargo Pants",
      oldPrice: 60,
      price: 48,
      quantity: 1,
      avlColors: ["green", "black"],
      src: "/data/Mens Next Light Stone Straight Fit Cotton Stretch Cargo Trousers -  light stone.jpeg",
      catigory: "pants",
      addedToCart: false,
      wished: false,
      discription: "Utility cargo pants with multiple pockets.",
    },
    {
      id: 36,
      name: "Straight Fit Jeans",
      oldPrice: 70,
      price: 55,
      quantity: 1,
      avlColors: ["blue", "dark blue"],
      src: "/data/Straight Fit Jean.jpeg",
      catigory: "pants",
      addedToCart: false,
      wished: false,
      discription: "Classic straight fit jeans.",
    },
  ],
];
export interface CartItem {
  id: number;
  name: string;
  oldPrice: number;
  price: number;
  quantity: number;
  avlColors: any;
  selectedColor?: string;
  src: string;
  src2?: string;
  src3?: string;
  catigory: string;
  addedToCart: boolean;
  wished: boolean;
  discription?: string;
}
